# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13da8e25a7ecf644d6e94d62529465d09fc43a24a3facfb70d106047125d6c96f10e321babfaeadd490abc43904ac566095aa5adf880f6657108a360a537a26c

test:
  secret_key_base: 95ca50f7232a8345279a8e907eac198bf9365f180dec3945355a3daf24765822f760aaf4348eb733d95c562b0c34cd0684e079407c2e7af48e7763c70e51d1d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
